//
// Created by oem on 9/29/21.
//

#ifndef RK_SQLLITE_METACOMMANDRESULT_H
#define RK_SQLLITE_METACOMMANDRESULT_H

enum MetaCommandResult {
  META_COMMAND_SUCCESS,
  META_COMMAND_UNRECOGNIZED_COMMAND
};

enum PrepareResult {
  PREPARE_SUCCESS,
  PREPARE_SYNTAX_ERROR,
  PREPARE_UNRECOGNIZED_STATEMENT
};

#endif //RK_SQLLITE_METACOMMANDRESULT_H
